language: generic
os: linux

env:
  global:
    var1: 1
    var2: 2
    var3: 3

script:
  - echo "s $var1 $var2 $var3 $var4"

after_success:
  - echo "af $var1 $var2 $var3 $var4"

after_script:
  - artifacts upload --target-paths "/" *.md
