language: minimal
os: linux

env:
  global:
    var1: 1
    var2: 2
    var3: 3

addons:
  artifacts: true
    target_paths:
      - /

script:
  - echo "s $var1 $var2 $var3 $var4" > generated_file_for_uploading.txt

after_success:
  - echo "af $var1 $var2 $var3 $var4"
